FROM quay.io/konveyor/builder:ubi9-latest AS builder

ENV GOPATH=/go \
    GOTOOLCHAIN=auto

WORKDIR /workspace

# Copy full repository (includes vendor/, Makefile, config/, bundle/, etc.)
COPY . .

# Prevent git safe directory errors if make bundle-ocp-ci queries git tags
RUN git config --global --add safe.directory /workspace

# Generate OCP bundle without overriding the pullspec set by the CI
RUN make bundle-ocp-ci

# Runtime bundle stage
FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=node-healthcheck-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.42.2
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v4

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

# Copy files generated by builder stage
COPY --from=builder /workspace/bundle/manifests /manifests/
COPY --from=builder /workspace/bundle/metadata /metadata/
COPY --from=builder /workspace/bundle/tests/scorecard /tests/scorecard/
