---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: dummy
  annotations:
    support: Red Hat
spec:
  maintainers:
  - email: team-dragonfly@redhat.com
    name: Dragonfly Team
  provider:
    name: Red Hat
    url: https://www.redhat.com
  links:
    - name: Node Healthcheck Operator
      url: https://www.medik8s.io/remediation/node-healthcheck-operator/node-healthcheck-operator/
    - name: Source Code
      url: https://github.com/medik8s/node-healthcheck-operator
