apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--http2-disable"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=0"
          - "--tls-cert-file=/etc/tls/private/tls.crt"
          - "--tls-private-key-file=/etc/tls/private/tls.key"
        volumeMounts:
          - name: tls-config
            mountPath: /etc/tls/private
            readOnly: true
      volumes:
        - name: tls-config
          secret:
            secretName: node-healthcheck-tls
