apiVersion: apps/v1
kind: Deployment
metadata:
  name: n/a
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - controller-manager
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - node-healthcheck-operator
                topologyKey: kubernetes.io/hostname
