name: CI

on:
  push:
  pull_request:
  # Ready for reuse from other repos once moved to medik8s/.github
  workflow_call: {}

permissions:
  contents: read

jobs:
  ci:
    uses: medik8s/.github/.github/workflows/ci.yaml@main
