name: Pre Submit
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  build-and-unit-test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: make manager

    - name: Verify no bundle changes and run unit-tests
      run: make manifests bundle-k8s bundle-reset test

    - name: Test container build K8s
      run: make container-build-k8s

    - name: Test container build OCP
      run: make container-build-ocp
